" Ui
" ================
syntax on
colorscheme shine 
set hls

" Coding
" ================
" show line and column number
set ruler 

" indent for C/C++
set autoindent
set cindent
set smartindent
" set tabstop=4
set shiftwidth=4
set expandtab

" Move lines up and down
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

" Auto change the working directory the same as the current file
set autochdir

" Let Backspace erase normally
set backspace=indent,eol,start
